limmihyun/gdhealth

src/main/resources/application.properties

application.properties file upload 설정 추가

[정인호] application.properties file upload 설정 추가

---

src/main/java/com/tree/gdhealth/customer/programreservation/Init.java
src/main/java/com/tree/gdhealth/customer/programreservation/controller/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/service/CalendarService.java
src/main/webapp/WEB-INF/view/customer/programreservation.jsp

[장현수] 프로그램 예약 밑작업 및 캘린더 완료

---

src/main/java/com/tree/gdhealth/customer/programreservation/controller/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/mapper/ProgramReservationMapper.java
src/main/java/com/tree/gdhealth/customer/programreservation/mapper/ProgramReservationMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/service/CalendarService.java
src/main/webapp/WEB-INF/view/customer/programreservation.jsp

[장현수] 프로그램 예약 캘린더에 프로그램명 및 회원수 표시

[장현수] 프로그램 예약 캘린더에 프로그램명 및 회원수 표시

---

src/main/java/com/tree/gdhealth/customer/programreservation/mapper/ProgramReservationMapper.xml
src/main/webapp/WEB-INF/view/customer/programreservation.jsp

[장현수] 프로그램 예약 캘린더 옆 리스트 출력

---

src/main/java/com/tree/gdhealth/customer/programreservation/controller/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/mapper/ProgramReservationMapper.java
src/main/java/com/tree/gdhealth/customer/programreservation/mapper/ProgramReservationMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/service/CalendarService.java
src/main/webapp/WEB-INF/view/customer/programreservation.jsp

[장현수] calendar옆 List에 정확한 내용들이 출력되지 않는 오류, calendar에 예약되지 않는 프로그램이 뜨지 않는 오류 등 해결

[장현수] 여러가지 오류 해결

---

src/main/java/com/tree/gdhealth/customer/programreservation/CalendarService.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProRsOneMapper.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProRsOneMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/ProRsOneService.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/vo/ProgramReservation.java
src/main/webapp/WEB-INF/view/customer/proRsOne.jsp

[장현수] 패키지 구조 수정

---

src/main/java/com/tree/gdhealth/branch/sportsequipment/BranchSportsEquipmentController.java
src/main/java/com/tree/gdhealth/branch/sportsequipment/BranchSportsEquipmentMapper.java
src/main/java/com/tree/gdhealth/branch/sportsequipment/BranchSportsEquipmentMapper.xml
src/main/java/com/tree/gdhealth/branch/sportsequipment/BranchSportsEquipmentServiceImpl.java
src/main/java/com/tree/gdhealth/branch/sportsequipment/IBranchSportsEquipmentService.java
src/main/java/com/tree/gdhealth/branch/sportsequipment/getOrderListResponseDto.java
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiController.java
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiMapper.java
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiMapper.xml
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiService.java
src/main/java/com/tree/gdhealth/vo/SportsEquipmentImg.java
src/main/java/com/tree/gdhealth/vo/SportsEquipmentOrder.java
src/main/webapp/WEB-INF/view/branch/include/body-upper-layout.jsp
src/main/webapp/WEB-INF/view/branch/sports-equipment/list.jsp
src/main/webapp/WEB-INF/view/branch/sports-equipment/order.jsp
개발노트[정인호].md

- 지점물품주문조회 페이지: BranchSportsEquipmentController.java, BranchSportsEquipmentServiceImpl.java, getOrderListResponseDto.java, list.jsp 외
- 그외 간단한 수정
close #48

[정인호]- 지점물품주문조회 페이지외

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationService.java
src/main/webapp/WEB-INF/view/customer/proRsOne.jsp

[장현수] 프로그램 예약 완성

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationService.java
src/main/webapp/WEB-INF/view/customer/myreservation.jsp

[장현수] 나의 예약 보기

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationService.java
src/main/webapp/WEB-INF/view/customer/myreservation.jsp
src/main/webapp/WEB-INF/view/customer/programreservation.jsp

[장현수] 이전 버튼, 일정 삭제 기능 추가
Closes #65

[장현수] 이전 버튼, 일정 삭제 기능 추가

---

src/main/webapp/WEB-INF/view/customer/myreservation.jsp
src/main/webapp/WEB-INF/view/customer/proRsOne.jsp

[장현수] css스타일 적용

---

src/main/java/com/tree/gdhealth/branch/programcalendar/BranchProgramCalendarController.java
src/main/java/com/tree/gdhealth/branch/programcalendar/BranchProgramCalendarMapper.xml
src/main/java/com/tree/gdhealth/branch/programcalendar/BranchProgramCalendarService.java
src/main/java/com/tree/gdhealth/branch/programcalendar/api/BranchProgramDateApiController.java
src/main/java/com/tree/gdhealth/branch/programcalendar/api/BranchProgramDateApiMapper.java
src/main/java/com/tree/gdhealth/branch/programcalendar/api/BranchProgramDateApiMapper.xml
src/main/java/com/tree/gdhealth/branch/programcalendar/api/BranchProgramDateApiService.java
src/main/java/com/tree/gdhealth/branch/programcalendar/vo/BranchProgramCalendar.java
src/main/java/com/tree/gdhealth/branch/programcalendar/vo/BranchProgramDate.java
src/main/java/com/tree/gdhealth/configuration/RestTemplateConfig.java
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiController.java
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiMapper.java
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiMapper.xml
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiService.java
src/main/webapp/WEB-INF/view/branch/program-calendar/home.jsp
개발노트[정인호].md

- 페이징 기능 추가
- BranchProgramCalendarService.java 리팩토링
- 오늘 날짜의 강조표시
- 프로그램 상세보기에서 매니저 변경기능 추가
close #69

[정인호] feat: 지점프로그램주간캘린더 기능추가 (#69)

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationRest.java
src/main/webapp/WEB-INF/view/customer/myreservation.jsp

[장현수] delete ajax로 구현, 삭제시 유효성 검사 추가

[장현수] delete ajax로 구현, 삭제시 유효성 검사 추가

---

src/main/java/com/tree/gdhealth/notice/NoticeController.java
src/main/java/com/tree/gdhealth/notice/NoticeMapper.xml
src/main/webapp/WEB-INF/view/notice/updateNotice.jsp

[임미현]notice 삽입, 수정, 삭제

---

src/main/java/com/tree/gdhealth/branch/programcalendar/BranchProgramCalendarController.java
src/main/java/com/tree/gdhealth/branch/sportsequipment/BranchSportsEquipmentController.java
src/main/java/com/tree/gdhealth/employee/login/EmpLoginController.java
src/main/java/com/tree/gdhealth/employee/login/EmpLoginMapper.java
src/main/java/com/tree/gdhealth/employee/login/EmpLoginMapper.xml
src/main/java/com/tree/gdhealth/employee/login/EmpLoginService.java
src/main/java/com/tree/gdhealth/employee/login/LoginEmployee.java
src/main/webapp/WEB-INF/header/header.jsp
개발노트[정인호].md

- 직원로그인 기능수정
- 은택님으로부터 [EmpLoginController.java] 를 인수받아 직원 로그인 기능을 수정함
- 로그인시 [LoginEmployee.java]를 세션에 저장
- (@SessionAttribute(name = "loginEmployee", required = false) LoginEmployee loginEmployee)으로 컨트롤러에서 사용가능하게 수정
close #88

[정인호] feat: 직원로그인 기능수정 (#88)

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationService.java
src/main/webapp/WEB-INF/view/customer/programreservation.jsp

[장현수] 예약자가 max일 경우, 자기 자신이 예약한 프로그램 일 경우 표시
Closes #80

[장현수] 예약자가 max일 경우, 자기 자신이 예약한 프로그램 일 경우 표시

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationService.java
src/main/webapp/WEB-INF/view/customer/proRsOne.jsp

[장현수] 중복신청, 자기자신이 신청한 예약일처리 / branchadd select로 변경 및 쿼리 수정 
Closes #96

[장현수] 중복신청, 자기자신이 신청한 예약일처리 / branchadd select로 변경 및 쿼리 수정

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationService.java
src/main/webapp/WEB-INF/view/customer/programreservation.jsp

[장현수] 프로그램 준비중 해결 및 현재 날짜보다 전 프로그램 표시 X
Closes #98

[장현수] 프로그램 준비중 해결 및 현재 날짜보다 전 프로그램 표시 X

---

pom.xml
src/main/java/com/tree/gdhealth/customer/customerattendance/CustomerAttendanceController.java
src/main/java/com/tree/gdhealth/customer/customerattendance/CustomerAttendanceMapper.java
src/main/java/com/tree/gdhealth/customer/customerattendance/CustomerAttendanceService.java
src/main/webapp/WEB-INF/view/customer/customerAttendanceForm.jsp

[정인호] fix: 브랜치정리용 커밋

---

src/main/java/com/tree/gdhealth/question/QuestionController.java
src/main/java/com/tree/gdhealth/question/QuestionMapper.java
src/main/java/com/tree/gdhealth/question/QuestionMapper.xml
src/main/java/com/tree/gdhealth/question/QuestionService.java
src/main/java/com/tree/gdhealth/vo/Review.java

[임미현]review(vo)오류 해결

---

src/main/webapp/WEB-INF/view/headoffice/include/sideBar.jsp

[정인호] chores: 본사 사이드바 링크 수정

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationService.java
src/main/webapp/WEB-INF/view/customer/programreservation.jsp

[장현수] List 전체적인 재구성

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationService.java
src/main/webapp/WEB-INF/view/customer/programreservation.jsp

[장현수] List 수정 및 오류 해결

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationService.java
src/main/webapp/WEB-INF/view/customer/programreservation.jsp

[장현수] 프로그램 예약 오류 수정 및 코드 수정
Closes #132

[장현수] 프로그램 예약 오류 수정 및 코드 수정

---

src/main/java/com/tree/gdhealth/branch/api/BranchApiMapper.java
src/main/java/com/tree/gdhealth/branch/api/BranchApiMapper.xml
src/main/java/com/tree/gdhealth/branch/api/BranchApiService.java
src/main/java/com/tree/gdhealth/branch/api/BranchRestApiController.java
src/main/java/com/tree/gdhealth/branch/dto/BranchRetrieveCriteria.java
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiMapper.java
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiMapper.xml
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiService.java
src/main/java/com/tree/gdhealth/employee/api/EmployeeRestApiController.java
src/main/java/com/tree/gdhealth/employee/dto/EmployeeRetrieveCriteria.java
src/main/java/com/tree/gdhealth/utils/ResponseEntityGenerator.java
src/main/java/com/tree/gdhealth/utils/exception/TooManyResultsException.java
src/test/java/com/tree/gdhealth/branch/api/BranchRestApiControllerTest.java
src/test/java/com/tree/gdhealth/employee/api/EmployeeRestApiControllerTest.java
개발노트[정인호].md

ResponseEntityGenerator 공통으로 작성
BranchRestApiControllerTest 작성
close #138

[정인호] refactor: branch, employee Api 리팩토링

---

src/main/java/com/tree/gdhealth/answer/AnswerController.java
src/main/java/com/tree/gdhealth/answer/AnswerMapper.java
src/main/java/com/tree/gdhealth/answer/AnswerMapper.xml
src/main/java/com/tree/gdhealth/answer/AnswerService.java
src/main/java/com/tree/gdhealth/question/QuestionController.java
src/main/java/com/tree/gdhealth/question/QuestionMapper.xml
src/main/java/com/tree/gdhealth/question/QuestionService.java
src/main/webapp/WEB-INF/header/header.jsp
src/main/webapp/WEB-INF/view/answer/answerOne.jsp
src/main/webapp/WEB-INF/view/question/questionList.jsp
src/main/webapp/WEB-INF/view/question/updateQuestion.jsp

[임미현]question add, update, delete

[임미현]question add, update, delete

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationRest.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationService.java
src/main/webapp/WEB-INF/view/customer/programreservation.jsp

[장현수] list ajax 기능 추가

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationRest.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationService.java
src/main/webapp/WEB-INF/view/customer/myreservation.jsp

[장현수]css 수정 및 delete ajax 기능 수정
Closes #149

[장현수]css 수정 및 delete ajax 기능 수정

---

src/main/java/com/tree/gdhealth/branch/BranchController.java
src/main/java/com/tree/gdhealth/branch/BranchServiceFacade.java
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiMapper.java
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiMapper.xml
src/main/java/com/tree/gdhealth/employee/api/EmployeeApiService.java
src/main/java/com/tree/gdhealth/employee/api/EmployeeRestApiController.java
src/main/java/com/tree/gdhealth/employee/dto/EmployeeInformation.java
src/main/java/com/tree/gdhealth/headoffice/sportsequipmentorder/SportsEquipmentOrderController.java
src/main/java/com/tree/gdhealth/program/ProgramApiMapper.java
src/main/java/com/tree/gdhealth/program/ProgramApiMapper.xml
src/main/java/com/tree/gdhealth/program/ProgramApiService.java
src/main/java/com/tree/gdhealth/program/dto/BranchProgramCalendar.java
src/main/java/com/tree/gdhealth/sportsequipment/SportsEquipmentApiMapper.java
src/main/java/com/tree/gdhealth/sportsequipment/SportsEquipmentApiMapper.xml
src/main/java/com/tree/gdhealth/sportsequipment/SportsEquipmentApiService.java
src/main/webapp/WEB-INF/view/branch/programCalendar.jsp
src/test/java/com/tree/gdhealth/branch/programcalendar/BranchProgramCalendarServiceTest.java
src/test/java/com/tree/gdhealth/employee/api/EmployeeRestApiControllerTest.java

외부 서비스를 의존하는 메소드를 분리, 퍼사드에 참조되도록 변경; ProgramApiService.java
지점 프로그램 캘린더 화면 이미지 보이게 변경
그 밖에 코드 가독성 관련 chores
close #154

[정인호] [정인호] refactor : 지점 프로그램 캘린더 API 서비스 리팩토링

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java
src/main/webapp/WEB-INF/view/customer/myreservation.jsp
src/main/webapp/WEB-INF/view/customer/programreservation.jsp
src/main/webapp/WEB-INF/view/customer/reservationCalendar.jsp

[장현수] calendar ajax 기능 추가 
Closes #152

[장현수] calendar ajax 기능 추가

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.xml
src/main/webapp/WEB-INF/view/customer/programreservation.jsp
src/main/webapp/WEB-INF/view/customer/reservationCalendar.jsp

[장현수] program_reservation 기능 마무리
Closes #163

[장현수] program_reservation 기능 마무리

---

src/main/java/com/tree/gdhealth/headoffice/membership/MembershipController.java
src/main/java/com/tree/gdhealth/headoffice/membership/MembershipMapper.java
src/main/java/com/tree/gdhealth/headoffice/membership/MembershipMapper.xml
src/main/java/com/tree/gdhealth/headoffice/membership/MembershipService.java
src/main/java/com/tree/gdhealth/headoffice/membership/init.java
src/main/java/com/tree/gdhealth/vo/Membership.java
src/main/webapp/WEB-INF/view/customer/proRsOne.jsp
src/main/webapp/WEB-INF/view/customer/programreservation.jsp
src/main/webapp/WEB-INF/view/headoffice/membershipList.jsp

[장현수] 회원권(membership) 생성 및 프로그램 예약 css 수정

[장현수] 회원권(membership) 생성 및 프로그램 예약 css 수정

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java
src/main/java/com/tree/gdhealth/headoffice/membership/MembershipController.java
src/main/java/com/tree/gdhealth/headoffice/membership/MembershipMapper.java
src/main/java/com/tree/gdhealth/headoffice/membership/MembershipMapper.xml
src/main/java/com/tree/gdhealth/headoffice/membership/MembershipService.java
src/main/java/com/tree/gdhealth/headoffice/membership/init.java
src/main/webapp/WEB-INF/view/headoffice/addMembership.jsp

[장현수] headoffice 회원권 add 및 list 추가 
Closes #170

[장현수] headoffice 회원권 add 및 list 추가

---

src/main/java/com/tree/gdhealth/question/QuestionController.java
src/main/java/com/tree/gdhealth/question/QuestionMapper.java
src/main/java/com/tree/gdhealth/question/QuestionMapper.xml
src/main/java/com/tree/gdhealth/question/QuestionService.java
src/main/webapp/WEB-INF/view/branch/include/body-upper-layout.jsp
src/main/webapp/WEB-INF/view/question/questionList.jsp

[임미현]비밀글 적용된 Question 완성

---

src/main/webapp/WEB-INF/view/question/questionList.jsp

[임미현]question 보완

---

src/main/java/com/tree/gdhealth/headoffice/membership/MembershipMapper.java
src/main/java/com/tree/gdhealth/headoffice/membership/MembershipMapper.xml
src/main/java/com/tree/gdhealth/headoffice/membership/MembershipRest.java
src/main/java/com/tree/gdhealth/vo/Membership.java
src/main/webapp/WEB-INF/view/headoffice/membershipList.jsp

[장현수] 오류 해결 및 비활성화 기능 추가
Closes #175

[장현수] 오류 해결 및 비활성화 기능 추가

---

src/main/java/com/tree/gdhealth/headoffice/membership/MembershipMapper.java
src/main/java/com/tree/gdhealth/headoffice/membership/MembershipMapper.xml
src/main/java/com/tree/gdhealth/headoffice/membership/MembershipRest.java
src/main/java/com/tree/gdhealth/headoffice/membership/MembershipService.java
src/main/webapp/WEB-INF/view/headoffice/membershipList.jsp

[장현수] 회원권 비활성화 ajax 기능 추가

---

src/main/java/com/tree/gdhealth/customer/payment/PaymentController.java
src/main/java/com/tree/gdhealth/customer/payment/PaymentMapper.java
src/main/java/com/tree/gdhealth/customer/payment/PaymentMapper.xml
src/main/java/com/tree/gdhealth/customer/payment/PaymentService.java
src/main/webapp/WEB-INF/view/customer/addPayment.jsp
src/main/webapp/WEB-INF/view/customer/membershipList.jsp
src/main/webapp/WEB-INF/view/headoffice/membershipList.jsp

[장현수] customer MembershipList 추가 
Closes #187

[장현수] customer MembershipList 추가

---

src/main/java/com/tree/gdhealth/answer/AnswerController.java
src/main/java/com/tree/gdhealth/answer/AnswerMapper.xml
src/main/java/com/tree/gdhealth/notice/NoticeController.java
src/main/java/com/tree/gdhealth/question/QuestionController.java
src/main/java/com/tree/gdhealth/review/ReviewController.java
src/main/java/com/tree/gdhealth/review/ReviewMapper.xml
src/main/java/com/tree/gdhealth/vo/Answer.java
src/main/webapp/WEB-INF/header/header.jsp
src/main/webapp/WEB-INF/view/answer/addAnswer.jsp
src/main/webapp/WEB-INF/view/answer/updateAnswer.jsp
src/main/webapp/WEB-INF/view/headoffice/include/sideBar.jsp
src/main/webapp/WEB-INF/view/notice/addNotice.jsp
src/main/webapp/WEB-INF/view/notice/noticeList.jsp
src/main/webapp/WEB-INF/view/notice/noticeOne.jsp
src/main/webapp/WEB-INF/view/notice/updateNotice.jsp

[임미현]Question, Notice 레벨 차등 세션적용/링크적용

[임미현]Question, Notice 레벨 차등 세션적용/링크적용

---

src/main/java/com/tree/gdhealth/customer/payment/PaymentController.java
src/main/webapp/WEB-INF/view/customer/addPayment.jsp
src/main/webapp/WEB-INF/view/customer/membershipList.jsp
src/main/webapp/WEB-INF/view/customer/success.jsp

[장현수] addPayment css 수정

---

src/main/webapp/WEB-INF/header/header.jsp
src/main/webapp/WEB-INF/view/customer/addPayment.jsp

[장현수] addPayment 코드 수정 및 header링크 추가

---

src/main/java/com/tree/gdhealth/customer/payment/PaymentController.java
src/main/java/com/tree/gdhealth/customer/payment/PaymentMapper.java
src/main/java/com/tree/gdhealth/customer/payment/PaymentMapper.xml
src/main/java/com/tree/gdhealth/customer/payment/PaymentService.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationController.java

[장현수] payment 추가 방식 전체적인 수정 
Closes #206

[장현수] payment 추가 방식 전체적인 수정

---

src/main/webapp/WEB-INF/view/customer/membershipList.jsp
src/main/webapp/WEB-INF/view/customer/myreservation.jsp
src/main/webapp/WEB-INF/view/headoffice/membershipList.jsp

[장현수] membership list css 수정
Closes #210

[장현수] membership list css 수정

---

src/main/java/com/tree/gdhealth/customer/payment/PaymentMapper.java
src/main/java/com/tree/gdhealth/customer/payment/PaymentMapper.xml
src/main/java/com/tree/gdhealth/customer/payment/PaymentRest.java
src/main/java/com/tree/gdhealth/customer/payment/PaymentService.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.java
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.xml
src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationService.java

[장현수] programreservation삭제시 review삭제 및 payment delete 추가 
Closes #220

[장현수] programreservation삭제시 review삭제 및 payment delete 추가

---

src/main/java/com/tree/gdhealth/customer/programreservation/ProgramReservationMapper.xml
src/main/webapp/WEB-INF/view/customer/membershipList.jsp

[장현수] 코드 수정

---

src/main/java/com/tree/gdhealth/customer/mypage/MyPageController.java
src/main/java/com/tree/gdhealth/notice/NoticeController.java
src/main/java/com/tree/gdhealth/notice/NoticeMapper.java
src/main/java/com/tree/gdhealth/notice/NoticeMapper.xml
src/main/java/com/tree/gdhealth/notice/NoticeService.java
src/main/java/com/tree/gdhealth/question/QuestionController.java
src/main/java/com/tree/gdhealth/question/QuestionMapper.java
src/main/java/com/tree/gdhealth/question/QuestionMapper.xml
src/main/java/com/tree/gdhealth/question/QuestionService.java
src/main/webapp/WEB-INF/view/answer/temp.jsp
src/main/webapp/WEB-INF/view/customer/myPage.jsp
src/main/webapp/WEB-INF/view/customer/updateMyPage.jsp
src/main/webapp/WEB-INF/view/headoffice/include/sideBar.jsp
src/main/webapp/WEB-INF/view/notice/addNotice.jsp
src/main/webapp/WEB-INF/view/notice/noticeList.jsp
src/main/webapp/WEB-INF/view/notice/noticeOne.jsp
src/main/webapp/WEB-INF/view/notice/updateNotice.jsp
src/main/webapp/WEB-INF/view/question/addQuestion.jsp
src/main/webapp/WEB-INF/view/question/questionList.jsp
src/main/webapp/WEB-INF/view/question/questionOne.jsp
src/main/webapp/WEB-INF/view/question/updateQuestion.jsp

[임미현]css 적용

---

src/main/webapp/WEB-INF/view/customer/membershipList.jsp

[장현수] css 수정

---

src/main/java/com/tree/gdhealth/answer/AnswerController.java
src/main/java/com/tree/gdhealth/customer/mypage/MyPageController.java
src/main/java/com/tree/gdhealth/customer/mypage/MyPageMapper.java
src/main/java/com/tree/gdhealth/customer/mypage/MyPageMapper.xml
src/main/java/com/tree/gdhealth/customer/mypage/MyPageService.java
src/main/webapp/WEB-INF/view/customer/myPage.jsp
src/main/webapp/WEB-INF/view/customer/updateMyPage.jsp
src/main/webapp/WEB-INF/view/question/questionList.jsp
src/main/webapp/WEB-INF/view/question/questionOne.jsp
src/main/webapp/WEB-INF/view/review/reviewList.jsp
src/main/webapp/WEB-INF/view/review/reviewOne.jsp

[임미현]MyPage 수정, css적용

---

src/main/java/com/tree/gdhealth/customer/mypage/MyPageController.java
src/main/java/com/tree/gdhealth/question/QuestionMapper.xml
src/main/webapp/WEB-INF/view/question/questionOne.jsp
src/main/webapp/WEB-INF/view/question/temp.jsp

[임미현] question 본인만 수정/삭제 가능

---

src/main/webapp/WEB-INF/view/notice/noticeList.jsp
src/main/webapp/WEB-INF/view/question/questionList.jsp
src/main/webapp/WEB-INF/view/review/reviewList.jsp

[임미현] 페이징 <다음>lastPage 제한

---

src/main/java/com/tree/gdhealth/customer/mypage/MyPageMapper.xml
src/main/java/com/tree/gdhealth/customer/mypage/MyPageService.java
src/main/webapp/WEB-INF/view/customer/myPage.jsp
src/main/webapp/WEB-INF/view/customer/updateMyPage.jsp

[임미현]pull을 위한 중간커밋

---

src/main/java/com/tree/gdhealth/review/ReviewController.java
src/main/java/com/tree/gdhealth/review/ReviewMapper.xml
src/main/java/com/tree/gdhealth/review/ReviewService.java
src/main/webapp/WEB-INF/view/review/addReview.jsp
src/main/webapp/WEB-INF/view/review/reviewList.jsp
src/main/webapp/WEB-INF/view/review/reviewOne.jsp

[임미현]Review 최종

---

src/main/webapp/WEB-INF/view/notice/noticeList.jsp
src/main/webapp/WEB-INF/view/notice/noticeOne.jsp

[임미현]css오류수정

---

src/main/java/com/tree/gdhealth/customer/mypage/MyPageController.java
src/main/java/com/tree/gdhealth/customer/mypage/MyPageMapper.java
src/main/java/com/tree/gdhealth/customer/mypage/MyPageMapper.xml
src/main/java/com/tree/gdhealth/customer/mypage/MyPageService.java
src/main/java/com/tree/gdhealth/vo/CustomerMyPage.java
src/main/webapp/WEB-INF/view/customer/myPage.jsp
src/main/webapp/WEB-INF/view/customer/temp.jsp
src/main/webapp/WEB-INF/view/customer/updateMyPage.jsp

[임미현]myPage_최종
